### PR TITLE
Remove old import and update import_tools

### PR DESCRIPTION
**Pull request by pradal**
Fix issue #49 
Solve problem of build in septo3d

### CODE REVIEW

**Review by mlabadie — COMMENTED** [review]
bug are not solve. When i test it. I get this error
```
KeyError: 1916:
  File "C:\Users\mlabadie\Documents\GitHub\openalea-incubator\septo3d\SConstruct", line 16:
    env = ALEASolution(options, tools)
  File "c:\users\mlabadie\miniconda3\envs\septo3d\lib\site-packages\openalea.sconsx-2.2.6-py3.8.egg\openalea\sconsx\config.py", line 374:
    compilerconf.UpdateOptions(compileroptions)
  File "c:\users\mlabadie\miniconda3\envs\septo3d\lib\site-packages\openalea.sconsx-2.2.6-py3.8.egg\openalea\sconsx\config.py", line 301:
    tool.option(opts)
  File "c:\users\mlabadie\miniconda3\envs\septo3d\lib\site-packages\openalea.sconsx-2.2.6-py3.8.egg\openalea\sconsx\tools\compiler.py", line 120:
    opts.Add(EnumVariable('MSVC_VERSION', 'Version ','' if not is_conda() else get_default_msvc(), allowed_values=sorted(MsvcVersion.values())+['']))
  File "c:\users\mlabadie\miniconda3\envs\septo3d\lib\site-packages\openalea.sconsx-2.2.6-py3.8.egg\openalea\sconsx\tools\compiler.py", line 50:
    return MsvcVersion[int(version)]
```

**Comment by pradal** [comment]
Could you give your version of MSVC?

**Comment by mlabadie** [comment]
> Could you give your version of MSVC?

Visual Studio Community 2017 v15.9.41

**Comment by pradal** [comment]
OK. This version is not considered in sconsx.
I have to add it:

https://github.com/openalea/sconsx/blob/master/src/openalea/sconsx/tools/compiler.py#L34

Le 29/11/2021 à 15:02, Marc LABADIE a écrit :

**Comment by mlabadie** [comment]
for information

<html>
<body>


isual C++ version | _MSC_VER
-- | --
Visual C++ 4.x | 1000
Visual C++ 5 | 1100
Visual C++ 6 | 1200
Visual C++ .NET | 1300
Visual C++ .NET 2003 | 1310
Visual C++ 2005 (8.0) | 1400
Visual C++ 2008 (9.0) | 1500
Visual C++ 2010 (10.0) | 1600
Visual C++ 2012 (11.0) | 1700
Visual C++ 2013 (12.0) | 1800
Visual C++ 2015 (14.0) | 1900
Visual C++ 2017 (15.0) | 1910
Visual C++ 2017 (15.3) | 1911
Visual C++ 2017 (15.5) | 1912
Visual C++ 2017 (15.6) | 1913
Visual C++ 2017 (15.7) | 1914
Visual C++ 2017 (15.8) | 1915
Visual C++ 2017 (15.9) | 1916
Visual C++ 2019 RTW (16.0) | 1920
Visual C++ 2019 (16.1) | 1921
Visual C++ 2019 (16.2) | 1922
Visual C++ 2019 (16.3) | 1923
Visual C++ 2019 (16.4) | 1924
Visual C++ 2019 (16.5) | 1925
Visual C++ 2019 (16.6) | 1926
Visual C++ 2019 (16.7) | 1927
Visual C++ 2019 (16.8) | 1928
Visual C++ 2019 (16.9) | 1928
Visual C++ 2019 (16.10) | 1929
Visual C++ 2019 (16.11) | 1929


</body>
</html>

**Comment by pradal** [comment]
I will update the code.

**Pull request merged**
